-- Rollback for 20260828000000_class_term_and_sync_columns.
-- Drops only what that migration added. Run the backfill's unlink step
-- first if you want to keep the containers but detach the rows.

ALTER TABLE "ScheduleTemplate" DROP CONSTRAINT IF EXISTS "ScheduleTemplate_classId_fkey";
DROP INDEX IF EXISTS "ScheduleTemplate_classId_idx";
ALTER TABLE "ScheduleTemplate" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "Subject" DROP CONSTRAINT IF EXISTS "Subject_classId_fkey";
DROP INDEX IF EXISTS "Subject_classId_idx";
ALTER TABLE "Subject" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "SubjectGoal" DROP CONSTRAINT IF EXISTS "SubjectGoal_classId_fkey";
DROP INDEX IF EXISTS "SubjectGoal_classId_idx";
ALTER TABLE "SubjectGoal" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "Resource" DROP CONSTRAINT IF EXISTS "Resource_classId_fkey";
DROP INDEX IF EXISTS "Resource_classId_idx";
ALTER TABLE "Resource" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "MasteryItem" DROP CONSTRAINT IF EXISTS "MasteryItem_classId_fkey";
DROP INDEX IF EXISTS "MasteryItem_classId_idx";
ALTER TABLE "MasteryItem" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "TutorModule" DROP CONSTRAINT IF EXISTS "TutorModule_classId_fkey";
DROP INDEX IF EXISTS "TutorModule_classId_idx";
ALTER TABLE "TutorModule" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "StudioNote" DROP CONSTRAINT IF EXISTS "StudioNote_classId_fkey";
DROP INDEX IF EXISTS "StudioNote_classId_idx";
ALTER TABLE "StudioNote" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "AiNote" DROP CONSTRAINT IF EXISTS "AiNote_classId_fkey";
DROP INDEX IF EXISTS "AiNote_classId_idx";
ALTER TABLE "AiNote" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "Project" DROP CONSTRAINT IF EXISTS "Project_classId_fkey";
DROP INDEX IF EXISTS "Project_classId_idx";
ALTER TABLE "Project" DROP COLUMN IF EXISTS "classId";
ALTER TABLE "Task" DROP CONSTRAINT IF EXISTS "Task_termId_fkey";
DROP INDEX IF EXISTS "Task_termId_idx";
ALTER TABLE "Task" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "ExamEvent" DROP CONSTRAINT IF EXISTS "ExamEvent_termId_fkey";
DROP INDEX IF EXISTS "ExamEvent_termId_idx";
ALTER TABLE "ExamEvent" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "Homework" DROP CONSTRAINT IF EXISTS "Homework_termId_fkey";
DROP INDEX IF EXISTS "Homework_termId_idx";
ALTER TABLE "Homework" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "DailySummary" DROP CONSTRAINT IF EXISTS "DailySummary_termId_fkey";
DROP INDEX IF EXISTS "DailySummary_termId_idx";
ALTER TABLE "DailySummary" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "WeeklySummary" DROP CONSTRAINT IF EXISTS "WeeklySummary_termId_fkey";
DROP INDEX IF EXISTS "WeeklySummary_termId_idx";
ALTER TABLE "WeeklySummary" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "MarkedDay" DROP CONSTRAINT IF EXISTS "MarkedDay_termId_fkey";
DROP INDEX IF EXISTS "MarkedDay_termId_idx";
ALTER TABLE "MarkedDay" DROP COLUMN IF EXISTS "termId";
ALTER TABLE "ReportCard" DROP CONSTRAINT IF EXISTS "ReportCard_termId_fkey";
DROP INDEX IF EXISTS "ReportCard_termId_idx";
ALTER TABLE "ReportCard" DROP COLUMN IF EXISTS "termId";

ALTER TABLE "User" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "User" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Song" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "Song" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Playlist" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "Playlist" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ReportCard" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "SubjectGrade" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "SubjectGrade" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Homework" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "StudioNote" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "TutorModule" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "QuizAttempt" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "QuizAttempt" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Project" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ProjectDoc" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ChatSession" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ChatMessage" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "ChatMessage" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ScheduleTemplate" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "ScheduleTemplate" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Task" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "Task" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "MarkedDay" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "MarkedDay" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "UserProgress" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "UserProgress" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Resource" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "Resource" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "ExamEvent" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "ExamEvent" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "WeeklySummary" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "WeeklySummary" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "DailySummary" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "DailySummary" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "MasteryItem" DROP COLUMN IF EXISTS "updatedAt";
ALTER TABLE "MasteryItem" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "StickyNote" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "AiNote" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "SubjectGoal" DROP COLUMN IF EXISTS "deletedAt";
ALTER TABLE "Subject" DROP COLUMN IF EXISTS "deletedAt";

DROP TABLE IF EXISTS "Term";
DROP TABLE IF EXISTS "Class";
